name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # Executa sempre que fizer push na branch main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Renomear login.html para index.html
        run: cp login.html index.html

      - name: Upload da p치gina para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Publica a raiz do reposit칩rio (onde est치 o index.html)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
