name: Veracode Upload Scan          # Nome do workflow na aba Actions do GitHub

on:
  workflow_dispatch:                # Permite rodar o workflow manualmente

jobs:
  upload_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Veracode Upload & Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6

        with:
          appname: "login-inseguro"            # Nome da aplicação na Veracode
          createprofile: true                  # Cria automaticamente o perfil, se não existir
          filepath: "codigo-php.zip"           # 👉 ENVIA SOMENTE o arquivo .zip com seu código PHP
          version: "1.0.${{ github.run_number }}"  # Versão automática
          vid: ${{ secrets.VERACODE_API_ID }}  # ID da API (guardado com segurança)
          vkey: ${{ secrets.VERACODE_API_KEY }}  # Chave da API (guardado com segurança)
