name: Veracode Fix

on:
  workflow_dispatch:  # Roda manualmente

jobs:
  fix_job:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar a existência do arquivo results.json
        run: |
          if [ ! -f results.json ]; then
            echo "results.json não encontrado. Certifique-se de que o Veracode Pipeline Scan foi executado previamente."
            exit 1
          else
            echo "results.json encontrado."
          fi

      - name: Executar Veracode Fix
        uses: veracode/veracode-fix@v1.0.3
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          inputFile: results.json
          source_base_path_1: './'
          fixType: batch
          debug: false
          prComment: false
          createPR: true
