name: Veracode Pipeline Scan - Teste Simples

on:
  push:
    branches: [main]

jobs:
  pipeline_scan:
    runs-on: ubuntu-latest

    steps:
      # Clona o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Compacta o projeto para envio ao Veracode
      - name: Compactar projeto
        run: zip -r login-inseguro.zip . -x '*.github/*'

      # Executa o Veracode Pipeline Scan e falha se houver vulnerabilidades altas ou críticas
      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: login-inseguro.zip
          debug: true
          fail_on_severity: "Very High,High"  # Falha automática do pipeline.
          json_output: true
          summary_output: true
          summary_output_file: results_summary.txt
