# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Veracode Pipeline Scan

# Define quando o workflow será executado
# Neste caso, ele roda automaticamente quando houver um "push" para a branch "main"
on:
  push:
    branches: [main]
    
jobs:
  # Nome do job
  pipeline_scan:
    # Ambiente onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Criar um pacote ZIP do código
      - name: Criar pacote ZIP do código
        run: zip -r sac.zip . -x ".git/*" ".github/*"

      # Executar o Veracode Pipeline Scan
      - name: Executar Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@d5dbb47cb0202d511be5fd10a04071d32f74ace6
        with:
          # Credenciais armazenadas nos Secrets do repositório
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}

          # Arquivo ZIP do projeto
          file: sac.zip

          # Modo de depuração
          debug: true

          # ⚠️ Faz o pipeline falhar se houver vulnerabilidades
          fail_build_on_vulnerabilities: true

          # ⚠️ Define a severidade mínima para falha (VeryHigh = crítica)
          fail_severity: VeryHigh
