# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Veracode Pipeline Scan

# Define quando o workflow será executado
# Neste caso, ele roda automaticamente quando houver um "push" para a branch "main"
on:
  push:
    branches: [main]

jobs:
  pipeline_scan:
    # Ambiente onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Criar um pacote ZIP do código
      - name: Criar pacote ZIP do código
        run: zip -r sac.zip . -x ".git/*" ".github/*"

      # Executar o Veracode Pipeline Scan
      - name: Veracode Pipeline-Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.18
        with:
          # Credenciais armazenadas nos Secrets do repositório
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}

          # Arquivo ZIP do projeto
          file: sac.zip

          # Modo de depuração (logs detalhados)
          debug: true

          # ⚠️ Faz o job falhar se forem encontradas vulnerabilidades
          fail_build: true

          # ⚠️ Severidade mínima que causará falha (VeryHigh e High)
          fail_on_severity: "VeryHigh,High"

          # Opcional: mostra resumo dos resultados no console
          summary_display: true

          # Opcional: salva resultados em JSON
          json_output: true
          json_output_file: results.json
          filtered_json_output_file: filtered_results.json
