name: Veracode Fix

on:
  workflow_dispatch:  # Roda manualmente

jobs:
  fix_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Executar Veracode Fix
        uses: veracode/veracode-fix@main
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          source-base-path: './'
