name: Veracode Pipeline Scan - Simples (falha se houver vulnerabilidades)

on:
  push:
    branches: [main]

jobs:
  pipeline_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compactar projeto
        run: zip -r login-inseguro.zip . -x '*.github/*'

      - name: Veracode Pipeline Scan (falha se houver vulnerabilidades)
        uses: veracode/Veracode-pipeline-scan-action@d5dbb47cb0202d511be5fd10a04071d32f74ace6
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: login-inseguro.zip
          fail_on_severity: "Medium,High,Very High"  # falha se houver essas severidades
          fail_build: true
